version: '3.8'
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 5432:${DB_PORT}
  api:
    container_name: api
    ports:
      - 3131:${PORT}
    build: .
    env_file:
      - .env
    depends_on:
      - db
volumes:
  pgdata:
