version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 5432:${DB_PORT}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  api:
    container_name: api
    ports:
      - 3131:${PORT}
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules/
    depends_on:
      - postgres
volumes:
  pgdata:
  node_modules:
